

package ui;

import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
public class MenuReportUI extends javax.swing.JFrame {

    Connection connection = null;
    public MenuReportUI() {
        initComponents();
        
        String HOST = "jdbc:mysql://localhost:3306/corel_bay";
        String USERNAME = "root";
        String PASSWORD = "earth";

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Error : " + e.getMessage());
        }

        try {
            connection = DriverManager.getConnection(HOST, USERNAME, PASSWORD);
            
            Statement sql = connection.createStatement();
            ResultSet set = sql.executeQuery("select * from menus");
            set.next();
            
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
        
        Map<String, Object> t = new HashMap<String, Object>();
     
        try {
            //Fill the report with parameter, connection and the stream reader
            JasperPrint jasperPrint = JasperFillManager.fillReport("C:\\Users\\Hp\\Documents\\NetBeansProjects\\MnOMS\\src\\ireports\\OurMenu.jasper", t, connection);
            //Viewer for JasperReport
            JRViewer jRViewer = new JRViewer(jasperPrint);
            //Insert viewer to a JInternalFrame to make it showable

            Container container = getContentPane();
            container.setLayout(new BorderLayout());
            container.add(jRViewer);


        } catch (JRException ex) {
            System.out.println("Error : " + ex.getMessage());

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReportUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
