package entity;
// Generated Jul 25, 2013 8:25:49 PM by Hibernate Tools 3.2.1.GA



/**
 * BarItemOrder generated by hbm2java
 */
public class BarItemOrder  implements java.io.Serializable {


     private Integer botNo;
     private Bot bot;
     private MenuItem menuItem;
     private int qty;

    public BarItemOrder() {
    }

    public BarItemOrder(Bot bot, MenuItem menuItem, int qty) {
       this.bot = bot;
       this.menuItem = menuItem;
       this.qty = qty;
    }
   
    public Integer getBotNo() {
        return this.botNo;
    }
    
    public void setBotNo(Integer botNo) {
        this.botNo = botNo;
    }
    public Bot getBot() {
        return this.bot;
    }
    
    public void setBot(Bot bot) {
        this.bot = bot;
    }
    public MenuItem getMenuItem() {
        return this.menuItem;
    }
    
    public void setMenuItem(MenuItem menuItem) {
        this.menuItem = menuItem;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


