package entity;
// Generated Jul 25, 2013 8:25:49 PM by Hibernate Tools 3.2.1.GA



/**
 * BarOrder generated by hbm2java
 */
public class BarOrder  implements java.io.Serializable {


     private Integer botNo;
     private int botTicketNo;
     private String itemNo;
     private int qty;

    public BarOrder() {
    }

    public BarOrder(int botTicketNo, String itemNo, int qty) {
       this.botTicketNo = botTicketNo;
       this.itemNo = itemNo;
       this.qty = qty;
    }
   
    public Integer getBotNo() {
        return this.botNo;
    }
    
    public void setBotNo(Integer botNo) {
        this.botNo = botNo;
    }
    public int getBotTicketNo() {
        return this.botTicketNo;
    }
    
    public void setBotTicketNo(int botTicketNo) {
        this.botTicketNo = botTicketNo;
    }
    public String getItemNo() {
        return this.itemNo;
    }
    
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


