package entity;
// Generated Jul 25, 2013 8:25:49 PM by Hibernate Tools 3.2.1.GA



/**
 * FoodOrder generated by hbm2java
 */
public class FoodOrder  implements java.io.Serializable {


     private Integer kotNo;
     private int kotTicketNo;
     private String itemNo;
     private int qty;

    public FoodOrder() {
    }

    public FoodOrder(int kotTicketNo, String itemNo, int qty) {
       this.kotTicketNo = kotTicketNo;
       this.itemNo = itemNo;
       this.qty = qty;
    }
   
    public Integer getKotNo() {
        return this.kotNo;
    }
    
    public void setKotNo(Integer kotNo) {
        this.kotNo = kotNo;
    }
    public int getKotTicketNo() {
        return this.kotTicketNo;
    }
    
    public void setKotTicketNo(int kotTicketNo) {
        this.kotTicketNo = kotTicketNo;
    }
    public String getItemNo() {
        return this.itemNo;
    }
    
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


