package entity;
// Generated Jul 25, 2013 8:25:49 PM by Hibernate Tools 3.2.1.GA



/**
 * FoodItemOrder generated by hbm2java
 */
public class FoodItemOrder  implements java.io.Serializable {


     private Integer kotNo;
     private Kot kot;
     private MenuItem menuItem;
     private int qty;

    public FoodItemOrder() {
    }

    public FoodItemOrder(Kot kot, MenuItem menuItem, int qty) {
       this.kot = kot;
       this.menuItem = menuItem;
       this.qty = qty;
    }
   
    public Integer getKotNo() {
        return this.kotNo;
    }
    
    public void setKotNo(Integer kotNo) {
        this.kotNo = kotNo;
    }
    public Kot getKot() {
        return this.kot;
    }
    
    public void setKot(Kot kot) {
        this.kot = kot;
    }
    public MenuItem getMenuItem() {
        return this.menuItem;
    }
    
    public void setMenuItem(MenuItem menuItem) {
        this.menuItem = menuItem;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


