package entity;
// Generated Jul 25, 2013 8:25:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MenuItem generated by hbm2java
 */
public class MenuItem  implements java.io.Serializable {


     private String itemNo;
     private Menus menus;
     private String price;
     private String description;
     private String availability;
     private Set foodItemOrders = new HashSet(0);
     private Set barItemOrders = new HashSet(0);

    public MenuItem() {
    }

	
    public MenuItem(String itemNo, Menus menus, String price, String description, String availability) {
        this.itemNo = itemNo;
        this.menus = menus;
        this.price = price;
        this.description = description;
        this.availability = availability;
    }
    public MenuItem(String itemNo, Menus menus, String price, String description, String availability, Set foodItemOrders, Set barItemOrders) {
       this.itemNo = itemNo;
       this.menus = menus;
       this.price = price;
       this.description = description;
       this.availability = availability;
       this.foodItemOrders = foodItemOrders;
       this.barItemOrders = barItemOrders;
    }
   
    public String getItemNo() {
        return this.itemNo;
    }
    
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }
    public Menus getMenus() {
        return this.menus;
    }
    
    public void setMenus(Menus menus) {
        this.menus = menus;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(String availability) {
        this.availability = availability;
    }
    public Set getFoodItemOrders() {
        return this.foodItemOrders;
    }
    
    public void setFoodItemOrders(Set foodItemOrders) {
        this.foodItemOrders = foodItemOrders;
    }
    public Set getBarItemOrders() {
        return this.barItemOrders;
    }
    
    public void setBarItemOrders(Set barItemOrders) {
        this.barItemOrders = barItemOrders;
    }

@Override
    public String toString() {
        return description;
    }

    @Override
    public boolean equals(Object obj) {
       return this.description.equals(obj.toString());
    }


}


