package entity;
// Generated Jul 25, 2013 8:25:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.swing.table.AbstractTableModel;

/**
 * Menus generated by hbm2java
 */
public class Menus  implements java.io.Serializable {


     private String menuId;
     private String description;
     private String image;
     private Set menuItems = new HashSet(0);

    public Menus() {
    }

	
    public Menus(String menuId, String description, String image) {
        this.menuId = menuId;
        this.description = description;
        this.image = image;
    }
    public Menus(String menuId, String description, String image, Set menuItems) {
       this.menuId = menuId;
       this.description = description;
       this.image = image;
       this.menuItems = menuItems;
    }
   
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getMenuItems() {
        return this.menuItems;
    }
    
    public void setMenuItems(Set menuItems) {
        this.menuItems = menuItems;
    }

@Override
    public String toString() {
        return description;
    }

    @Override
    public boolean equals(Object obj) {
       return this.description.equals(obj.toString());
    }


}


