package entity;
// Generated Jul 25, 2013 8:25:49 PM by Hibernate Tools 3.2.1.GA



/**
 * Rooms generated by hbm2java
 */
public class Rooms  implements java.io.Serializable {


     private String roomNo;
     private String custNo;

    public Rooms() {
    }

    public Rooms(String roomNo, String custNo) {
       this.roomNo = roomNo;
       this.custNo = custNo;
    }
   
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }
    public String getCustNo() {
        return this.custNo;
    }
    
    public void setCustNo(String custNo) {
        this.custNo = custNo;
    }

@Override
    public String toString() {
        return roomNo;
    }

    @Override
    public boolean equals(Object obj) {
       return this.roomNo.equals(obj.toString());
    }


}


